
package com.webservice.cxf.client.wsdl2java;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-03T18:08:32.546+08:00
 * Generated source version: 3.3.2
 *
 */
public final class Greeting_GreetingImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.cxf.webservice.com/", "GreetingImplService");

    private Greeting_GreetingImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GreetingImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GreetingImplService ss = new GreetingImplService(wsdlURL, SERVICE_NAME);
        Greeting port = ss.getGreetingImplPort();

        {
        System.out.println("Invoking greeting...");
        java.lang.String _greeting_username = "";
        java.lang.String _greeting__return = port.greeting(_greeting_username);
        System.out.println("greeting.result=" + _greeting__return);


        }

        System.exit(0);
    }

}
