
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.webservice.cxf.client.wsdl2java;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-03T18:08:32.578+08:00
 * Generated source version: 3.3.2
 *
 */

@javax.jws.WebService(
                      serviceName = "GreetingImplService",
                      portName = "GreetingImplPort",
                      targetNamespace = "http://server.cxf.webservice.com/",
                      wsdlLocation = "http://localhost:8080/webservice/Greeting?wsdl",
                      endpointInterface = "com.webservice.cxf.client.wsdl2java.Greeting")

public class GreetingImplPortImpl implements Greeting {

    private static final Logger LOG = Logger.getLogger(GreetingImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see Greeting#greeting(java.lang.String username)*
     */
    public java.lang.String greeting(java.lang.String username) {
        LOG.info("Executing operation greeting");
        System.out.println(username);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
