
package com.webservice.cxf.client.wsdl2java;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-03T18:08:32.626+08:00
 * Generated source version: 3.3.2
 *
 */

public class Greeting_GreetingImplPort_Server{

    protected Greeting_GreetingImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new GreetingImplPortImpl();
        String address = "http://localhost:8080/webservice/Greeting";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new Greeting_GreetingImplPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
